version: '3.8'

services:
  pdf-to-markdown:
    build: ./pdf_to_markdown_service
    container_name: pdf-to-markdown-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /app/pdf_uploads:/app/pdf_uploads

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - pdf-to-markdown