version: '3.8'

services:
  ocr-service-problem-2:
    build: ./ocr_service_problem_2
    container_name: pdf2fhir
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./pdf_uploads:/app/pdf_uploads
      - ./fhir_results_problem_2:/app/fhir_results_problem_2

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ocr-service-problem-2